version: "3.9"

services:

  php:
    image: wodby/php:latest
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - "88:80"
    depends_on:
      - php
      - mariadb
    volumes:
      - ./:/var/www/html
      - ./docker:/etc/nginx/conf.d
    links:
      - php

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - "8080:80"

volumes:
  mariadb_data:
